# Generated by Django 3.0.5 on 2020-05-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_action'),
        ('news', '0003_auto_20200512_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='action_img/news/')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Slider_small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='action_img/slider_main/')),
                ('active', models.BooleanField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
            ],
            options={
                'verbose_name': 'Боковый баннер',
                'verbose_name_plural': 'Боковые баннеры',
            },
        ),
        migrations.CreateModel(
            name='Slider_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='action_img/slider_main/')),
                ('active', models.BooleanField()),
                ('title', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
            ],
            options={
                'verbose_name': 'Главный слайдер',
                'verbose_name_plural': 'Главный слайдер',
            },
        ),
    ]
