# Generated by Django 3.0.5 on 2020-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nomber_card',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
